### ISSUE TITLE
Can't pull blood essence, says multiple results be more specific.

### ISSUE THREAD

**Issue by lordKushnu** [Odjit/KindredLogistics#10]
Multiple items have "Blood Essence" in them, so it doesn't let me pull the basic blood essence

**Comment by mfoltz** [comment]
![IMG_2710](https://github.com/user-attachments/assets/94b3f33f-1e39-4fb5-9a53-b93337106492)
Feel free to reopen issue if attached image doesn’t adequately address your problem here.
