### ISSUE TITLE
Conveyor doesn't seem to work.

### ISSUE THREAD

**Issue by d6rks1lv3rz3r0** [Odjit/KindredLogistics#6]
Hi,

I got all other functions to work and a very helpful mod so far. I am having trouble getting the conveyor function to work.

To test, I made this chest:
![image](https://github.com/Odjit/KindredLogistics/assets/49707789/f0350bb5-6845-44e3-ad32-620681b49783)

Then, I made this tannery:
![image](https://github.com/Odjit/KindredLogistics/assets/49707789/c191e5e7-e53e-4402-998f-341f2deb6965)

I restarted, replaced stuff, toggled things on/off with `.l co` etc. nothing seems to get it started. I would appreciate a hand.

Thanks for your effort and time.

SilverZero

**Comment by Odjit** [comment]
Are you the actual owner of the plot you are testing this out on, not just clanned?

**Comment by d6rks1lv3rz3r0** [comment]
This is clan owned, but I am also the owner of the clan.

**Comment by d6rks1lv3rz3r0** [comment]
Ah, turns out the person who placed the original castle heart matters. When I kicked people out of my clan, I became an enemy. I suspect the game thinks the person who first placed the heart as the owner of everything. This is probably it. I'll report back after I try again.

**Comment by d6rks1lv3rz3r0** [comment]
Indeed this was the problem. Thanks for the help. 

Summary for future reference:
**You need to be the person who placed the castle heart to be able to do conveyor settings on a castle.**
