### ISSUE TITLE
autoStashMissions doesn't appear to work

### ISSUE THREAD

**Issue by soosticus** [Odjit/KindredLogistics#7]
We're running 1.0.2 via valhost.  autoStashMissions is enabled.  Servants don't seem to want to deposit to any storage, not even the "Spoils"  overflow bin (i'm using the 56 slot cupboard if the storage bin matters).

![image](https://github.com/Odjit/KindredLogistics/assets/1721803/ba0a12a3-2503-436e-b15c-25891ac5dfaf)

**Comment by mfoltz** [comment]
are you using the most recent version on Thunderstore?

**Comment by soosticus** [comment]
we were using 1.0.2 as provided by valhost.net.  they updated to 1.0.3 and it's fixed there. closing.
